### ISSUE TITLE
Missing translations are being included as empty strings

### ISSUE THREAD

**Issue by JasonBarnabe** [transifex/cli#248]
I use `tx pull -a -f` (version 1.6.17) to pull in the content for [devise-i18n](https://github.com/devise-i18n/devise-i18n). Transifex project is at https://app.transifex.com/devise-i18n/devise-i18n-1.

Some content has no translation yet. I'm expecting these translation keys to be excluded in the translation files pulled with `tx`. Instead, they're being included with empty strings. This breaks the library I'm using to handle these translations, as an empty string does not fall back to the English version.

Example: https://app.transifex.com/devise-i18n/devise-i18n-1/translate/#bg/enyml/565570122

Current start of the file:

```
bg:
  activerecord:
    attributes:
      user:
        confirmation_sent_at: ""
        confirmation_token: ""
        confirmed_at: ""
        created_at: ""
        current_password: Настояща парола
```

Expected start of the file

```
bg:
  activerecord:
    attributes:
      user:
        current_password: Настояща парола
```

Alternate expected start of file:

```
bg:
  activerecord:
    attributes:
      user:
        confirmation_sent_at:
        confirmation_token:
        confirmed_at:
        created_at:
        current_password: Настояща парола
```

I have [another project](https://app.transifex.com/greasy-fork/greasy-fork/dashboard/) that uses this same command, but I don't have the issue there.
